export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FALURE = "LOGIN_FALURE";
export const LOGOUT = "LOGOUT";
export const FALHA = "FALHA";
export const PERSIST_TOKEN = "PERSIST_TOKEN";

export const HISTORICO_REQUEST = "HISTORICO_REQUEST";
export const HISTORICO_SUCCESS = "HISTORICO_SUCCESS";
export const HISTORICO_FALURE = "HISTORICO_FALURE";

export const HISTORICO_CADASTRAR_REQUEST = "HISTORICO_CADASTRAR_REQUEST";
export const HISTORICO_CADASTRAR_SUCCESS = "HISTORICO_CADASTRAR_SUCCESS";
export const HISTORICO_CADASTRAR_FALURE = "HISTORICO_CADASTRAR_FALURE";

export const HISTORICO_EDITAR_REQUEST = "HISTORICO_EDITAR_REQUEST";
export const HISTORICO_EDITAR_SUCCESS = "HISTORICO_EDITAR_SUCCESS";
export const HISTORICO_EDITAR_FALURE = "HISTORICO_EDITAR_FALURE";

export const HISTORICO_DELETAR_REQUEST = "HISTORICO_DELETAR_REQUEST";
export const HISTORICO_DELETAR_SUCCESS = "HISTORICO_DELETAR_SUCCESS";
export const HISTORICO_DELETAR_FALURE = "HISTORICO_DELETAR_FALURE";

export const MONITORAMENTO_REQUEST = "MONITORAMENTO_REQUEST";
export const MONITORAMENTO_SUCCESS = "MONITORAMENTO_SUCCESS";
export const MONITORAMENTO_FALURE = "MONITORAMENTO_FALURE";

//-----

export const MENSAGEM_REQUEST = "MENSAGEM_REQUEST";
export const MENSAGEM_SUCCESS = "MENSAGEM_SUCCESS";
export const MENSAGEM_FALURE = "MENSAGEM_FALURE";

export const MENSAGEM_CADASTRAR_REQUEST = "MENSAGEM_CADASTRAR_REQUEST";
export const MENSAGEM_CADASTRAR_SUCCESS = "MENSAGEM_CADASTRAR_SUCCESS";
export const MENSAGEM_CADASTRAR_FALURE = "MENSAGEM_CADASTRAR_FALURE";

export const MENSAGEM_EDITAR_REQUEST = "MENSAGEM_EDITAR_REQUEST";
export const MENSAGEM_EDITAR_SUCCESS = "MENSAGEM_EDITAR_SUCCESS";
export const MENSAGEM_EDITAR_FALURE = "MENSAGEM_EDITAR_FALURE";

export const MENSAGEM_DELETAR_REQUEST = "MENSAGEM_DELETAR_REQUEST";
export const MENSAGEM_DELETAR_SUCCESS = "MENSAGEM_DELETAR_SUCCESS";
export const MENSAGEM_DELETAR_FALURE = "MENSAGEM_DELETAR_FALURE";

